# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :certificates do
  match(type: "development", app_identifier: ["me.dutour.mathieu.TimeLine", "me.dutour.mathieu.TimeLine.TimeLine-Widget"], force_for_new_devices: true)
  match(type: "appstore", app_identifier: ["me.dutour.mathieu.TimeLine", "me.dutour.mathieu.TimeLine.TimeLine-Widget"])
end

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do
    if ENV["CI"] then
      create_keychain(
        name: "GithubActionKeychain",
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        add_to_search_list: true
      )
      match(
        keychain_name: "GithubActionKeychain",
        keychain_password: ENV["MATCH_PASSWORD"],
        type: "appstore",
        app_identifier: "me.dutour.mathieu.TimeLine",
        readonly: true
      )
    else
      match(type: "appstore")
    end
  end

  lane :beta do
    increment_build_number(build_number: ENV["BUILD_NUMBER"], xcodeproj: "TimeLine.xcodeproj")
    build_app(
      project: "TimeLine.xcodeproj",
      scheme: "TimeLine",
      include_bitcode: true,
      xcargs: "\"FASTLANE_BUILD\"=\"YES\""
    )
    upload_to_testflight(skip_waiting_for_build_processing: true, apple_id: "1474784231")
  end

  after_all do
    if ENV["CI"] then
      delete_keychain(
        name: "GithubActionKeychain"
      )
    end
  end
end
