# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus",
  "iPhone 11 Pro Max",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (3rd generation)",
])

languages([
  "en-US",
  "fr-FR",
  "es-ES",
])

# don't use concurrent simulators otherwise it fails with
# "Lost connection to the application". (https://github.com/fastlane/fastlane/issues/13657)
concurrent_simulators(false)

# Choose which project/workspace to use
workspace "./TimeLine.xcodeproj"

# The name of the scheme which contains the UI Tests
scheme("TimeLineUITests")

# Pass some args to xcodebuild so that we can skip linting and such
xcargs("\"FASTLANE_SNAPSHOT\"=\"YES\"")

# Where should the resulting screenshots be stored?
output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# For more information about all available options run
# fastlane action snapshot
